### ISSUE TITLE
Handling for MqttPassword / Passwords in general

### ISSUE THREAD

**Issue by deveth0** [tobias-richter/ansible-tasmota#14]
Hey,

when setting the mqtt password using the ansible role, it is detected as change each time. Also the password is published in plaintext inside the playbook output:

```
changed: [tasmota_balkon_chirp] => (item={'command': 'MqttPassword', 'value': 'blubblub'})
```

I'm not sure, if we can solve the first problem, is there any best practive if such configs should return a "changed" or "ok"? 
```
22:06:34.603 CMD: mqttpassword
22:06:34.611 MQT: stat/tasmota_balkon_chirp/RESULT = {"MqttPassword":"****"}
```

For the second problem:  It is also relevant for the following configs:

- Password<x>
- WebPassword

I guess we could set the `no_log` flag for all commands that contain "password", what do you think?

**Comment by tobias-richter** [comment]
I am not using the role to set MqttPassword or other credentials.
My approach would be to use the normal `no_log` pattern.

Item definition
```
- command: MqttPassword
  value: "LoremIpsum"
  no_log: True
```
Task:
```
- name: "Configure tasmota."
  tasmota:
    command: "{{ item.command }}"
    value: "{{ item.value }}"
    no_log: "{{ item.no_log | default(True) }}"
  with_items: "{{ tasmota_commands }}"
```
I did a quick test and it not working out of the box so there is something missing.

Regarding the changed / not changed output of the password I have not really an opinion. If you have the feeling that a not changed output is the correct output in this case you can implement a PR for this. Another solution would be to make the "changed" result overwritable via a task variable:

```
- name: "Configure tasmota."
  tasmota:
    command: "{{ item.command }}"
    value: "{{ item.value }}"
    changed: "{{ item.report_changed | default(omit) }}"
  with_items: "{{ tasmota_commands }}"
```

ℹ️ Please note that the command MqttPassword will restart the device. The Role does currently not handle restarts so this must also be implemented.

Feel free to implement a PR for this. Since the issue does not touch my usecases and I have currently not that much time I will not spend any effort in a solution :)
