### ISSUE TITLE
Ansible-tasmota crashing on macOS 12.2.1 (21D62)

### ISSUE THREAD

**Issue by user34756361233** [tobias-richter/ansible-tasmota#27]
When running:

```
ansible-playbook playbooks/adjust_reporting_tasmotas.yaml
```
with the following playbook

```
- hosts: tasmotas
  gather_facts: no
  tasks:
    - name: Ensure device reports status
      include_role:
        name: tobias_richter.tasmota  
      vars:
        tasmota_commands:
          - command: Teleperiod
            value: 200
```

I get the following error:  

```
han@MBP2018-2 Ansible % ansible-playbook playbooks/upgrade_tasmotas.yaml

PLAY [tasmotas] ***********************************************************************************************************************************************************

TASK [Ensure device reports status] ***************************************************************************************************************************************

TASK [tobias_richter.tasmota : Configure tasmota.] ************************************************************************************************************************
objc[75669]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[75669]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

This is related to:

https://github.com/ansible/ansible/issues/32499 : OSX crash complaining of operation in progress in another thread when fork() was called #32499

Ist there anything I can do to prevent the error so this playbook is run?
